config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "kittens#index"
  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.json { render :json => @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render :json => @kitten }
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])
    @kitten.attributes = kitten_params
    if @kitten.save
      redirect_to @kitten, flash: { congrats: "Successfully updated!" }
    else
      flash[:scorn] = "You put a bad value!"
      render :edit, status: :unprocessable_entity
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.create(kitten_params)
    if @kitten.save
      redirect_to @kitten, flash: { congrats: "Successfully created!" }
    else
      flash[:scorn] = "You put a bad value!"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy

    redirect_to root_path, flash: { congrats: "Successfully destroyed!" }
  end

  private
  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with model: kitten do |f| %>
  <%= f.label :name, "Name:" %>
  <%= f.text_field :name %><br><br>
  <%= f.label :age, "Age:" %>
  <%= f.number_field :age %><br><br>
  <%= f.label :cuteness, "Cuteness:" %>
  <%= f.number_field :cuteness%><br><br>
  <%= f.label :softness, "Softness:" %>
  <%= f.number_field :softness%><br><br>
  <%= f.submit %>
<% end %>

app/views/kittens/_kitten.html.erb
<p>
<b><%= link_to(kitten.name, kitten) %></b> | 
<%= link_to "Delete", kitten_path(kitten), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %><br>
Age: <i><%= kitten.age %></i> | Cuteness: <i><%= kitten.cuteness %></i> | Softness: <i><%= kitten.softness %></i>
</p>

app/views/kittens/edit.html.erb
<h1>Edit Kitten #<%= @kitten.id %></h1>
<%= render "kittens/form", kitten: @kitten %><br>
<%= button_to "Delete Kitten", @kitten, method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } } %>

app/views/kittens/index.html.erb
<h1>Kittens Index:</h1>
<%= render @kittens %>

app/views/kittens/new.html.erb
<h1>New Kitten:</h1>
<%= render "kittens/form", kitten: @kitten %>

app/views/kittens/show.html.erb
<h1><%= @kitten.name %></h1>
<p>Age: <%= @kitten.age %></p>
<p>Cuteness: <%= @kitten.cuteness %></p>
<p>Softness: <%= @kitten.softness %></p>
<%= button_to "Delete Kitten", @kitten, method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: name %>
    <% end %>
    <%= yield %>
  </body>
</html>